const Animals = [
    'сat', 'kitten',
    'dog', 'puppy',
    'hamster', 'parrot',
    'guineapig', 'chicken',
    'rooster', 'turkey',
    'gobbler', 'goat',
    'billygoat', 'kid',
    'sheep', 'ram',
    'lamb', 'bull',
    'cow', 'calf',
    'horse', 'stallon',
    'colt', 'mare',
    'pig', 'sow',
    'piglet', 'rabbit',
    'kit', 'doe',
    'buck', 'crocodile',
    'deer', 'elephant',
    'elk', 'fox',
    'giraffe', 'hare',
    'hippopotamus', 'hyena',
    'jaguar', 'leopard',
    'lion', 'lynx',
    'marten', 'mink',
    'mole', 'mongoose',
    'monkey', 'mouse',
    'hedgehog', 'otter',
    'panda', 'panther',
    'puma', 'raccoon',
    'rhinoceros', 'sable',
    'squirrel', 'tiger',
    'tortoise', 'wolf',
    'yak', 'zebra',
    'triton', 'piranha',
    'scorpion', 'salamander',
    'chameleon', 'tarantula',
    'capybara', 'alligator',
    'ostrich', 'penguin',
    'snake', 'lizard',
    'chinchilla', 'kangaroo'
];
const Jobs = [
'actor', 'actress',
'architect', 'artist',
'attorney', 'banker',
'bartender', 'barber',
'bookkeeper', 'builder',
'businessman', 'businesswoman',
'businessperson', 'butcher',
'carpenter', 'cashier',
'chef', 'coach',
'dentist', 'designer',
'developer', 'dietician',
'doctor', 'economist',
'editor', 'electrician',
'engineer', 'accountant'
];
let secretWord = [];
let wrongLetters = [];